In [62]:
import pandas as pd
import json
from transformers import AutoTokenizer
from datasets import load_dataset

In [63]:
results_file = "tacred_scores_numind___NuNER-v2.0"
model_name = results_file.replace("tacred_scores_", "").replace("___", "/")

In [64]:
def asym_jaccard_similarity(L1, L2, beta = 0.5, add_ngrams = 0):
    if add_ngrams > 1:
        L1 = L1 + [" ".join(L1[i:i+add_ngrams]) for i in range(len(L1) - add_ngrams + 1)]
        L2 = L2 + [" ".join(L2[i:i+add_ngrams]) for i in range(len(L2) - add_ngrams + 1)]
        
    return len(set(L1) & set(L2)) / (len(set(L1))*beta + len(set(L2))*(1-beta))

In [65]:
tokenizer = AutoTokenizer.from_pretrained(model_name)
data = load_dataset("xiaobendanyn/tacred", split = "test")
df = pd.DataFrame([json.loads(d['text']) for d in data]).map(lambda x: x['name'] if isinstance(x, dict) else " ".join(x) if isinstance(x, list) else x)
df.rename(columns = {"token": "input", "relation": "label"}, inplace = True)
df["h_tokens"] = df["h"].apply(lambda x: tokenizer.tokenize(x, add_special_tokens = False))
df["t_tokens"] = df["t"].apply(lambda x: tokenizer.tokenize(x, add_special_tokens = False))
df.head()

,input,h,t,label,h_tokens,t_tokens
0,The National Congress of American Indians was ...,National Congress of American Indians,1944,org:founded,"[National, ĠCongress, Ġof, ĠAmerican, ĠIndians]","[19, 44]"
1,UASR was founded in 1989 by Mousa abu Mazook <...,UASR,1989,org:founded,"[U, AS, R]",[1989]
2,"Founded in 1951 , PATA is a non-profit members...",PATA,1951,org:founded,"[P, ATA]","[19, 51]"
3,The Securities and Exchange Commission schedul...,Countrywide,1969,org:founded,"[Country, wide]",[1969]
4,"MEF , which was founded in 1991 , has grabbed ...",MEF,1991,org:founded,"[ME, F]",[1991]

In [66]:
results = pd.read_json(f"../src/results/{results_file}.json")
results["tokenized"] = results["original_text"].apply(lambda x: tokenizer.tokenize(x, add_special_tokens = False))
results["e_i_tokens"] = results.apply(lambda row: row["tokenized"][row["e_i_idx"][0]:row["e_i_idx"][1]], axis = 1)
results["e_j_tokens"] = results.apply(lambda row: row["tokenized"][row["e_j_idx"][0]:row["e_j_idx"][1]], axis = 1)
results = results.loc[results["e_j_tokens"].apply(len) > 1,:]
results.head()

,e_i_idx,e_j_idx,e_i_tokens,e_j_tokens,score,original_text,doc_number,tokenized
0,"[3, 4]","[5, 10]",[Ġof],"[ĠIndians, Ġwas, Ġfounded, Ġin, Ġ1944]",0.000000,The National Congress of American Indians was ...,0,"[The, ĠNational, ĠCongress, Ġof, ĠAmerican, ĠI..."
1,"[3, 4]","[11, 24]",[Ġof],"[Ġresponse, Ġto, Ġass, imilation, Ġpolicies, Ġ...",1.000000,The National Congress of American Indians was ...,0,"[The, ĠNational, ĠCongress, Ġof, ĠAmerican, ĠI..."
2,"[5, 10]","[11, 24]","[ĠIndians, Ġwas, Ġfounded, Ġin, Ġ1944]","[Ġresponse, Ġto, Ġass, imilation, Ġpolicies, Ġ...",0.013487,The National Congress of American Indians was ...,0,"[The, ĠNational, ĠCongress, Ġof, ĠAmerican, ĠI..."
3,"[1, 7]","[8, 44]","[AS, R, Ġwas, Ġfounded, Ġin, Ġ1989]","[ĠMous, a, Ġab, u, ĠMaz, ook, Ġ<, Ġhttp, ://, ...",0.000000,UASR was founded in 1989 by Mousa abu Mazook <...,3,"[U, AS, R, Ġwas, Ġfounded, Ġin, Ġ1989, Ġby, ĠM..."
4,"[1, 7]","[45, 47]","[AS, R, Ġwas, Ġfounded, Ġin, Ġ1989]","[ĠSyria, Ġ,]",1.000000,UASR was founded in 1989 by Mousa abu Mazook <...,3,"[U, AS, R, Ġwas, Ġfounded, Ġin, Ġ1989, Ġby, ĠM..."

In [67]:
text_match = pd.merge(df, results, left_on = "input", right_on = "original_text", how = "inner")
df.shape[0], results.shape[0], text_match.shape[0]

(15509, 17475, 109755)

In [72]:
# Joint df and results on rows that have input==original_text and jaccard_similarity(h_tokens, e_i_tokens) >= 0.5 and jaccard_similarity(t_tokens, e_j_tokens) >= 0.5
jaccard_threshold = 0.5
low_filter_threshold = 0.25
precision_advantage = 2/3
ngram_length = 2

text_match['low_filter'] = text_match.apply(lambda row: asym_jaccard_similarity(row['h_tokens'] + row['t_tokens'], row["e_i_tokens"] + row["e_j_tokens"], beta = precision_advantage, add_ngrams = ngram_length), axis = 1)
text_match = text_match.loc[text_match['low_filter'] > low_filter_threshold,:]
print("Remaining samples: ", text_match.shape[0])

text_match['h_match'] = text_match.apply(lambda row: asym_jaccard_similarity(row['h_tokens'], row["e_i_tokens"], beta = precision_advantage, add_ngrams = ngram_length), axis = 1)
text_match['t_match'] = text_match.apply(lambda row: asym_jaccard_similarity(row['t_tokens'], row["e_j_tokens"], beta = precision_advantage, add_ngrams = ngram_length), axis = 1)
both_matches = (text_match['h_match'] > jaccard_threshold) & (text_match['t_match'] > jaccard_threshold)

text_match['h_inverse_match'] = text_match.apply(lambda row: asym_jaccard_similarity(row['h_tokens'], row["e_j_tokens"], beta = precision_advantage, add_ngrams = ngram_length), axis = 1)
text_match['t_inverse_match'] = text_match.apply(lambda row: asym_jaccard_similarity(row['t_tokens'], row["e_i_tokens"], beta = precision_advantage, add_ngrams = ngram_length), axis = 1)
both_inverse_matches = (text_match['h_inverse_match'] > jaccard_threshold) & (text_match['t_inverse_match'] > jaccard_threshold)

final_matches = both_matches | both_inverse_matches

all_scores_df = text_match.fillna(0)
all_scores_df['y_true'] = final_matches.astype(int)
all_scores_df.loc[all_scores_df['label'] == "NA", 'y_true'] = -1
all_scores_df['y_true'].value_counts() / all_scores_df.shape[0]

Remaining samples:  3050

y_true
-1    0.761967
 0    0.233770
 1    0.004262
Name: count, dtype: float64

In [73]:
all_scores_df.loc[all_scores_df['y_true'] == 1, :].sample(10)

,input,h,t,label,h_tokens,t_tokens,e_i_idx,e_j_idx,e_i_tokens,e_j_tokens,score,original_text,doc_number,tokenized,low_filter,h_match,t_match,h_inverse_match,t_inverse_match,y_true
5553,"Arnold survives him , along with three childre...",Joseph I. Lange,Arnold,per:parents,"[Joseph, ĠI, ., ĠLange]","[Ar, n, old]","[1, 3]","[29, 37]","[n, old]","[ĠA, ., ĠLange, Ġ;, Ġand, ĠJoseph, ĠI, .]",0.000000e+00,"Arnold survives him , along with three childre...",10923,"[Ar, n, old, Ġsurvives, Ġhim, Ġ,, Ġalong, Ġwit...",0.545455,0.000000,0.000000,0.535714,0.692308,1
97461,"Michael Gibbons , Chairman of the National Res...",National Restaurant Association,Michael Gibbons,org:top_members/employees,"[National, ĠRestaurant, ĠAssociation]","[Michael, ĠGib, bons]","[1, 5]","[6, 10]","[ĠGib, bons, Ġ,, ĠChairman]","[Ġthe, ĠNational, ĠRestaurant, ĠAssociation]",0.000000e+00,"Michael Gibbons , Chairman of the National Res...",13869,"[Michael, ĠGib, bons, Ġ,, ĠChairman, Ġof, Ġthe...",0.486486,0.000000,0.000000,0.529412,0.529412,1
102392,Panama has submitted a letter of intention to ...,Central American Parliament,PARLACEN,org:alternate_names,"[Central, ĠAmerican, ĠParliament]","[PAR, L, AC, EN]","[12, 16]","[17, 22]","[ĠAmerican, ĠParliament, Ġ-, L]","[-, ĠPAR, L, AC, EN]",9.699893e-08,Panama has submitted a letter of intention to ...,14034,"[Pan, ama, Ġhas, Ġsubmitted, Ġa, Ġletter, Ġof,...",0.571429,0.529412,0.652174,0.000000,0.142857,1
6528,Miettinen hired for WPS champ Sky Blue FC,Miettinen,Sky Blue FC,per:employee_of,"[M, iet, t, inen]","[Sky, ĠBlue, ĠFC]","[1, 4]","[8, 20]","[iet, t, inen]","[Ġchamp, ĠSky, ĠBlue, ĠFC]",0.000000e+00,Miettinen hired for WPS champ Sky Blue FC,7556,"[M, iet, t, inen, Ġhired, Ġfor, ĠW, PS, Ġchamp...",0.615385,0.789474,0.529412,0.000000,0.000000,1
96888,National Taiwan Symphony Orchestra -LRB- NTSO ...,National Taiwan Symphony Orchestra,Liu Suan-yung,org:top_members/employees,"[National, ĠTaiwan, ĠSymphony, ĠOrchestra]","[L, iu, ĠSu, an, -, y, ung]","[1, 4]","[5, 22]","[ĠTaiwan, ĠSymphony, ĠOrchestra]","[L, RB, -, ĠNTS, O, Ġ-, RR, B, -, Ġleader, ĠLi...",1.270212e-22,National Taiwan Symphony Orchestra -LRB- NTSO ...,5836,"[National, ĠTaiwan, ĠSymphony, ĠOrchestra, Ġ-,...",0.607595,0.789474,0.526316,0.000000,0.000000,1
6656,Wayne A. Holst teaches at the University of Ca...,Wayne A. Holst,St. David 's United Church,per:employee_of,"[Way, ne, ĠA, ., ĠHol, st]","[St, ., ĠDavid, Ġ', s, ĠUnited, ĠChurch]","[1, 8]","[9, 21]","[ne, ĠA, ., ĠHol, st, Ġteaches, Ġat]","[ĠUniversity, Ġof, ĠCalgary, Ġand, Ġat, ĠSt, ....",0.000000e+00,Wayne A. Holst teaches at the University of Ca...,1208,"[Way, ne, ĠA, ., ĠHol, st, Ġteaches, Ġat, Ġthe...",0.686747,0.771429,0.673469,0.066667,0.076923,1
1131,"The sole survivor , 9-year-old Ruben van Assou...",Ruben van Assouw,9-year-old,per:age,"[Rub, en, Ġvan, ĠAss, ou, w]","[9, -, year, -, old]","[1, 9]","[10, 15]","[Ġsole, Ġsurvivor, Ġ,, Ġ9, -, year, -, old]","[en, Ġvan, ĠAss, ou, w]",6.999566e-21,"The sole survivor , 9-year-old Ruben van Assou...",14421,"[The, Ġsole, Ġsurvivor, Ġ,, Ġ9, -, year, -, ol...",0.703125,0.000000,0.000000,0.870968,0.600000,1
1136,"The sole survivor , 9-year-old Ruben van Assou...",Ruben van Assouw,9-year-old,per:age,"[Rub, en, Ġvan, ĠAss, ou, w]","[9, -, year, -, old]","[10, 15]","[24, 32]","[en, Ġvan, ĠAss, ou, w]","[Ġparents, Ġand, Ġ11, -, year, -, old, Ġbrother]",0.000000e+00,"The sole survivor , 9-year-old Ruben van Assou...",14421,"[The, Ġsole, Ġsurvivor, Ġ,, Ġ9, -, year, -, ol...",0.703125,0.870968,0.600000,0.000000,0.000000,1
3722,"Nuclear Decommissioning Authority , http://www...",Nuclear Decommissioning Authority,http://www.nda.gov.uk,org:website,"[N, uclear, ĠDec, omm, ission, ing, ĠAuthority]","[http, ://, www, ., nda, ., gov, ., uk]","[1, 7]","[8, 27]","[uclear, ĠDec, omm, ission, ing, ĠAuthority]","[Ġhttp, ://, www, ., nda, ., gov, ., uk]",0.000000e+00,"Nuclear Decommissioning Authority , http://www...",735,"[N, uclear, ĠDec, omm, ission, ing, ĠAuthority...",0.847059,0.891892,0.866667,0.000000,0.000000,1
106237,Youth minister and `` Street General '' Charle...,Charles Ble Goude,Youth minister,per:title,"[Charles, ĠBle, ĠG, oud, e]","[Y, outh, Ġminister]","[1, 3]","[4, 15]","[outh, Ġminister]","[Ġ``, ĠStreet, ĠGeneral, Ġ'', ĠCharles, ĠBle, ...",3.294299e-08,Youth minister and `` Street General '' Charle...,12357,"[Y, outh, Ġminister, Ġand, Ġ``, ĠStreet, ĠGene...",0.545455,0.000000,0.000000,0.538462,0.692308,1

In [74]:
all_scores_df['rel_presence'] = all_scores_df['y_true'].apply(lambda x: "correct" if x == 1 else "incorrect" if x == 0 else "no relation")
from math import log
# Label -1 means correctly found entities with no relation in the dataset, while 0 means incorrectly found entities which should therefore have no relation
log_table = all_scores_df[['rel_presence', 'score']].pivot(columns = "rel_presence", values = "score").map(lambda x: log(x + 1e-10))
print(log_table.describe())

rel_presence       correct     incorrect   no relation
count         1.300000e+01  7.130000e+02  2.324000e+03
mean         -2.027935e+01 -1.698143e+01 -1.649703e+01
std           6.538876e+00  9.315110e+00  9.484308e+00
min          -2.302585e+01 -2.302585e+01 -2.302585e+01
25%          -2.302585e+01 -2.302585e+01 -2.302585e+01
50%          -2.302585e+01 -2.302585e+01 -2.302585e+01
75%          -2.302585e+01 -9.356453e+00 -8.149701e+00
max           1.000000e-10  1.000000e-10  1.000000e-10

In [78]:
import seaborn as sns
import matplotlib.pyplot as plt
f, ax = plt.subplots(figsize = (10, 10))
sns.boxplot(x = "rel_presence", y = "score", data = all_scores_df, orient = "v", log_scale=True, ax = ax)
ax.set_title(f"Score distribution for model: {model_name}")
ax.set_xlabel("Label")
ax.set_ylabel("Score (log-scale)")
f.savefig(f"score_distribution_{model_name.replace('/', '___')}.pdf")

/home/is/davide-r/.pyenv/versions/3.12.8/envs/beer/lib/python3.12/site-packages/numpy/lib/_function_base_impl.py:4653: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)